src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Repository\EntrepriseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EntrepriseRepository::class)]
class Entreprise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $raisonSociale = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateCreation = null;

    #[ORM\Column(length: 100)]
    private ?string $adresse = null;

    #[ORM\Column(length: 20)]
    private ?string $cp = null;

    #[ORM\Column(length: 50)]
    private ?string $ville = null;

    /**
     * @var Collection<int, Employe>
     */
    #[ORM\OneToMany(targetEntity: Employe::class, mappedBy: 'entreprise', orphanRemoval: true)]
    #[ORM\OrderBy(['nom' => 'ASC'])]
    private Collection $employes;

    public function __construct()
    {
        $this->employes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raisonSociale;
    }

    public function setRaisonSociale(string $raisonSociale): static
    {
        $this->raisonSociale = $raisonSociale;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): static
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getDateCreationFr(): string
    {
        return $this->dateCreation?->format('d/m/Y');
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): static
    {
        $this->cp = $cp;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getAdresseComplete(): string
    {
        return $this->adresse.', '.$this->cp.' - '.$this->ville;
    }

    /**
     * @return Collection<int, Employe>
     */
    public function getEmployes(): Collection
    {
        return $this->employes;
    }

    public function addEmploye(Employe $employe): static
    {
        if (!$this->employes->contains($employe)) {
            $this->employes->add($employe);
            $employe->setEntreprise($this);
        }

        return $this;
    }

    public function removeEmploye(Employe $employe): static
    {
        if ($this->employes->removeElement($employe)) {
            // set the owning side to null (unless already changed)
            if ($employe->getEntreprise() === $this) {
                $employe->setEntreprise(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->raisonSociale;
    }
}

src/Form/EntrepriseType.php
<?php

namespace App\Form;

use App\Entity\Entreprise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class EntrepriseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('raisonSociale', TextType::class, [
                'attr' => [
                    'class' => 'form-control'],
            ])
            ->add('dateCreation', DateType::class, [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-control'],
            ])
            ->add('adresse', TextType::class, [
                'attr' => [
                    'class' => 'form-control'],
                ])
            ->add('cp', TextType::class, [
                'attr' => [
                    'class' => 'form-control'],
                ])
            ->add('ville', textType::class, [
                'attr' => [
                    'class' => 'form-control'],
                ])
                ->add('valider', SubmitType::class, [
                    'attr' => [
                        'class' => 'btn btn-primary'],
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Entreprise::class,
        ]);
    }
}

src/Controller/EntrepriseController.php
<?php

namespace App\Controller;

use App\Entity\Entreprise;
use App\Form\EntrepriseType;
use App\Repository\EntrepriseRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class EntrepriseController extends AbstractController
{
    #[Route('/entreprise', name: 'app_entreprise')]
    public function index(EntrepriseRepository $entrepriseRepository): Response
    {
        
        $entreprises = $entrepriseRepository->findBy([], ["raisonSociale" => "ASC"]);
        return $this->render('entreprise/index.html.twig', [
            'entreprises' => $entreprises,
            'description' => 'Liste des entreprises'
        ]);
    }
    
    #[Route('/entreprise/new', name: 'new_entreprise')]
    #[Route('/entreprise/{id}/edit', name: 'edit_entreprise')]
    public function new_edit(Entreprise $entreprise = null, Request $request, EntityManagerInterface $entityManager): Response
    {
        if(!$entreprise) {

            $entreprise = new Entreprise();
        
        }

        $form = $this->createForm(EntrepriseType::class, $entreprise);
        
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
        
            $entreprise = $form->getData();

            $entityManager->persist($entreprise);
        
            $entityManager->flush();

            return $this->redirectToRoute('app_entreprise');
        }

        return $this->render('entreprise/new.html.twig', [
            'formAddEntreprise' => $form,
            'edit'=> $entreprise->getId(),
            'description' => 'Création d’une nouvelle entreprise'
        ]);
    }

    #[Route('/entreprise/{id}/delete', name: 'delete_entreprise')]
    public function delete(Entreprise $entreprise, EntityManagerInterface $entityManager): Response
    {
        
        $entityManager->remove($entreprise);

        $entityManager->flush();

        return $this->redirectToRoute('app_entreprise');
    }


    #[Route('/entreprise/{id}', name: 'show_entreprise')]
    public function show(Entreprise $entreprise): Response
    {
        return $this->render('entreprise/show.html.twig', [
            'entreprise' => $entreprise,
            'description' => 'Détail de l’entreprise : '.$entreprise
        ]);
    }
}

templates/entreprise/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des entreprises{% endblock %}

{% block body %}
    <h1>Liste des entreprises</h1>

    <a href="{{ path('new_entreprise') }}" class="btn btn-success">Ajouter une entreprise</a><br>

   {% for entreprise in entreprises %}
        <a href="{{ path('show_entreprise', {'id' : entreprise.id }) }}">{{ entreprise }}</a>
        <a class="btn btn-warning" href="{{ path('edit_entreprise', {'id' : entreprise.id }) }}">Editer</a>
        <a class="btn btn-danger" href="{{ path('delete_entreprise', {'id' : entreprise.id}) }}">Supprimer</a><br>
   {% endfor %}

{% endblock %}

templates/entreprise/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter une entreprise{% endblock %}

{% block body %}

    {% if edit %}
    
        <h1>Editer une entreprise</h1>

    {% else %}

        <h1>Ajouter une entreprise</h1>
    
    {% endif %}

    {# {{ form(formAddEntreprise) }} #}

    {{ form_start(formAddEntreprise) }}
    
        {{ form_row(formAddEntreprise.raisonSociale) }}
        {{ form_row(formAddEntreprise.dateCreation) }}
    
        <div class="row">

                {{ form_row(formAddEntreprise.adresse) }}

            <div class="col-sm">
                {{ form_row(formAddEntreprise.cp) }}
            </div>
            <div class="col-sm">
                {{ form_row(formAddEntreprise.ville) }}
            </div>
        </div>
        {{ form_row(formAddEntreprise.valider) }}
    {{ form_end(formAddEntreprise) }}

{% endblock %}

templates/entreprise/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail de l'entreprise : {{ entreprise }} {% endblock %}

{% block body %}
    <h1>Détail de l'entreprise : {{ entreprise }} </h1>

    <p>
        Adresse : {{ entreprise.adresseComplete }}<br>
        Date de création : {{ entreprise.dateCreation | date('d/m/Y') }}
    </p>

    <h3>Liste des salariés</h3>
    {% if entreprise.employes|length > 0 %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Employé</th>
                </tr>
            </thead>
            <tbody>
                {% for employe in entreprise.employes %}
                    <tr><td><a href="{{ path('show_employe', {'id' : employe.id}) }}">{{ employe }}</a></td></tr> <br>
                {% endfor %}
            </tbody>
        </table>

    {% else %}
        <p>Aucun salarié dans cette entreprise.</p>
    {% endif %}

{% endblock %}